kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-web-r
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-r
subjects:
- kind: User
  namespace: web
  name: apidev@msftopenhack7111ops.onmicrosoft.com
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-api-rw
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-rw
subjects:
- kind: User
  namespace: api
  name: apidev@msftopenhack7111ops.onmicrosoft.com