apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrysiq8419.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: password
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: servername
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: databasename
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
        ports:
        - containerPort: 80
          name: userprofile