# read/write access to web ns
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-rw
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---  
# read access to api ns
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-r
  namespace: api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
