apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /api/poi
        pathType: Prefix
        backend:
          service:
            name: poi
            port:
              number: 80
      - path: /api/trips
        pathType: Prefix
        backend:
          service:
            name: trips-svc
            port:
              number: 80
      - path: /api/user-java # this api paths was got from the code
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /api/user # this api paths was got from the code. Dont get confused with the service name
        pathType: Prefix
        backend:
          service:
            name: userprofile-svc
            port:
              number: 80
