apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  namespace: insurance
  labels:
    deploy: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - image: "registrysiq8419.azurecr.io/insurance:1.0"
        imagePullPolicy: Always
        name: insurance
        resources:
          limits:
            memory: 2048Mi
            cpu: 500m
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP