apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: openhack-key-vault
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: openhack-key-vault       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"           # use the defaults from the doc
    userAssignedIdentityID: "14092f3d-b5a5-4622-80ff-8ccd1f1c7c72"   
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: username     # In this example, 'ExampleSecret' 
          objectAlias: SQL_USER  
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: password    # In this example, 'ExampleSecret'   
          objectAlias: SQL_PASSWORD
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""   
        - |
          objectName: servername     # In this example, 'ExampleSecret'   
          objectAlias: SQL_SERVER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""   
        - |
          objectName: dbname    # In this example, 'ExampleSecret'   
          objectAlias: SQL_DBNAME
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""   
    tenantId: "5fd38e9f-c2f8-4c2e-b13b-9e86e6e82e0a"               # the tenant ID containing the Azure Key Vault instance