apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: registrysiq8419.azurecr.io/tripinsights/user-java:1.0
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        # resources:
        #   limits:
        #     memory: 256Mi
        #     cpu: 200m
        ports:
        - containerPort: 80
          name: user
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "openhack-key-vault"